### ISSUE TITLE
Can't patch the BIG-IP image

### ISSUE THREAD

**Issue by jreg2k** [F5Networks/f5-openstack-image-prep#36]
Hello,

I am trying to patch the BIGIP-11.6.1.0.0.317.ALL.qcow2.zip image to run BIG-IP on Openstack. After running : 

> python ve_image_sync.py -i /home/james/BIGIP-11.6.1.0.0.317.qcow2

or 

> sudo /bin/bash patch-image.sh -s /home/james/f5-openstack-image-prep/lib/f5_image_prep/
> startup.tar -f /home/james/BIGIP-11.6.1.0.0.317.qcow2 

the image is not patched. The script runs well but the image is the same as the original.

The output is here 

> sudo /bin/bash patch-image.sh -s /home/james/f5-openstack-image-prep/lib/f5_image_prep/
> startup.tar -f /home/james/BIGIP-11.6.1.0.0.317.qcow2 /home/james/BIGIP-11.6.1.0.0.317.qcow2
- '[' -n '' ']'
- echo 'BASE_ISO_FILE : '
  BASE_ISO_FILE : 
- '[' -n '' ']'
- check_oldfile_full_path
- '[' -f /home/james/BIGIP-11.6.1.0.0.317.qcow2 ']'
  ++ basename /home/james/BIGIP-11.6.1.0.0.317.qcow2
- ofname=BIGIP-11.6.1.0.0.317.qcow2
- '[' -z ']'
  ++ newfilename BIGIP-11.6.1.0.0.317.qcow2
  +++ basename BIGIP-11.6.1.0.0.317.qcow2
  ++ local ofname=BIGIP-11.6.1.0.0.317.qcow2
  ++ '[' -n '' ']'
  ++ local hotfixisofile=
  ++ '[' -z '' ']'
  +++ echo BIGIP-11.6.1.0.0.317.qcow2
  +++ sed 's/(.*).qcow2/\1-OpenStack.qcow2/'
  ++ newfile=BIGIP-11.6.1.0.0.317-OpenStack.qcow2
  ++ echo BIGIP-11.6.1.0.0.317-OpenStack.qcow2
- newfile=BIGIP-11.6.1.0.0.317-OpenStack.qcow2
- cp /home/james/BIGIP-11.6.1.0.0.317.qcow2 /home/james/.f5-image-prep/tmp/BIGIP-11.6.1.0.0.317-OpenStack.qcow2
- sleep 2
- qemu-nbd -d /dev/nbd0
  /dev/nbd0 disconnected
- sleep 2
- qemu-nbd --connect=/dev/nbd0 /home/james/.f5-image-prep/tmp/BIGIP-11.6.1.0.0.317-OpenStack.qcow2
- sleep 2
- pvscan
  PV /dev/sda5   VG ubuntu-vg       lvm2 [49.52 GiB / 0    free]
  Total: 1 [49.52 GiB] / in use: 1 [49.52 GiB] / in no VG: 0 [0   ]
- sleep 2
- echo 'The following command may cause '\''Can'\''t deactivate'\'' messages.'
  The following command may cause 'Can't deactivate' messages.
- echo 'These do not necessarily indicate a problem.'                                                                         [550/1987]
  These do not necessarily indicate a problem.
- vgchange -ay
  2 logical volume(s) in volume group "ubuntu-vg" now active
- sleep 2
- mkdir -p /mnt/bigip-config
- '[' -n '' ']'
- echo 'Waiting 15 seconds'
  Waiting 15 seconds
- sleep 15
- umount /mnt/bigip-config
  umount: /mnt/bigip-config: not mounted
- '[' 32 -eq 1 ']'
- umount /mnt/bigip-shared
  umount: /mnt/bigip-shared: mountpoint not found
- '[' 32 -eq 1 ']'
  ++ get_dev set.1._config
  ++ ls -l /dev/vg-db-hda
  ++ cut -d/ -f2-
  ++ cut '-d>' -f2
  ls: cannot access '/dev/vg-db-hda': No such file or directory
  ++ grep set.1._config
- mount /dev/ /mnt/bigip-config
  mount:  /dev is not a block device
- inject_files
- '[' -f /home/james/f5-openstack-image-prep/lib/f5_image_prep/startup.tar ']'
- tar -xf /home/james/f5-openstack-image-prep/lib/f5_image_prep/startup.tar -C /mnt/bigip-config/
- true
- touch /mnt/bigip-config/firstboot
- '[' -f none ']'
- '[' -n '' ']'
- '[' -n '' ']'
- sleep 2
- umount /mnt/bigip-config
  umount: /mnt/bigip-config: not mounted
- sleep 2
- '[' -n '' ']'
- sleep 2
- vgchange -an
  
  Logical volume ubuntu-vg/root contains a filesystem in use.
  Can't deactivate volume group "ubuntu-vg" with 2 open logical volume(s)
- sleep 2
- qemu-nbd -d /dev/nbd0
  /dev/nbd0 disconnected
- echo 'Patched image located at /home/james/.f5-image-prep/tmp/BIGIP-11.6.1.0.0.317-OpenStack.qcow2'
  Patched image located at /home/james/.f5-image-prep/tmp/BIGIP-11.6.1.0.0.317-OpenStack.qcow2
- set +x

Any help will be appreciated.

Regards.

**Comment by pjbreaux** [comment]
What version of Ubuntu are you testing this on @jreg2k?
