### ISSUE TITLE
setup.py install does not require openstack clients

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-image-prep#60]
The setup.py installation of this repo does not require the proper python client libraries for glance and keystone. This is currently done in the f5-openstack-heat template with an apt-get install (which is not correct). We'll move it to the setup.py here and then update the heat template to remove that installation. The other big point is that we are installation from latest with apt-get, so we're unsure of what we're getting when we do the heat template install. With the setup.py change, we'll fix it to a particular version that is tested and works.

**Comment by dflanigan** [comment]
@pjbreaux, is this currently a problem or do you think that this will cause a problem in the future ?

**Comment by pjbreaux** [comment]
@dflanigan: both. It needs to be addressed soon, especially since are are going to move into newton.

**Comment by dflanigan** [comment]
Created a jira issue for this.
